version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./auth/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth/.htpasswd:/etc/nginx/.htpasswd:ro

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      MYSQL_DATABASE: gitea
    volumes:
      - ./db:/var/lib/mysql

  gitea:
    image: gitea/gitea:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"   # Web UI
      - "222:22"      # Git over SSH (optional)
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
