version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./auth/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth/.htpasswd:/etc/nginx/.htpasswd:ro

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
      MYSQL_DATABASE: gitea
    volumes:
      - ./db:/var/lib/mysql

  gitea:
    image: gitea/gitea:latest
    depends_on:
      - db
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data

  postgredb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_postgres:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube_prac
    depends_on:
      - postgredb
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgredb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  gitea-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_postgres:
